/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: T-FLEX CAD ST (Free) (https://sketchfab.com/tflexcad)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/internal-combustion-engine-moto-ebd1dab5fd3745b58c031aecd9a4d640
title: Internal Combustion Engine Moto
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CombustionEngine(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/models/engines/combustionEngine/scene.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group
          position={[-0.08, -0.17, -0.09]}
          rotation={[-Math.PI / 2, Math.PI / 2, 0]}
        >
          <mesh geometry={nodes.mesh_0.geometry} material={materials.App6D7} />
          <mesh geometry={nodes.mesh_1.geometry} material={materials.App7F6} />
          <mesh geometry={nodes.mesh_2.geometry} material={materials.App836} />
          <mesh geometry={nodes.mesh_3.geometry} material={materials.App915} />
          <mesh geometry={nodes.mesh_4.geometry} material={materials.AppC47} />
          <mesh geometry={nodes.mesh_5.geometry} material={materials.AppAE6} />
          <mesh geometry={nodes.mesh_6.geometry} material={materials.AppB56} />
          <mesh geometry={nodes.mesh_7.geometry} material={materials.AppBF7} />
          <mesh geometry={nodes.mesh_8.geometry} material={materials.AppCF7} />
          <mesh geometry={nodes.mesh_9.geometry} material={materials.AppDE7} />
          <mesh geometry={nodes.mesh_10.geometry} material={materials.AppEC5} />
          <mesh geometry={nodes.mesh_11.geometry} material={materials.AppF65} />
          <mesh geometry={nodes.mesh_12.geometry} material={materials.App935} />
          <mesh geometry={nodes.mesh_13.geometry} material={materials.App667} />
          <mesh geometry={nodes.mesh_14.geometry} material={materials.App0A7} />
          <mesh geometry={nodes.mesh_15.geometry} material={materials.App6C1} />
          <mesh geometry={nodes.mesh_16.geometry} material={materials.App156} />
          <mesh geometry={nodes.mesh_17.geometry} material={materials.AppFA4} />
          <mesh
            geometry={nodes.mesh_18.geometry}
            material={nodes.mesh_18.material}
          />
          <mesh
            geometry={nodes.mesh_19.geometry}
            material={nodes.mesh_19.material}
          />
          <mesh
            geometry={nodes.mesh_20.geometry}
            material={nodes.mesh_20.material}
          />
          <mesh
            geometry={nodes.mesh_21.geometry}
            material={nodes.mesh_21.material}
          />
          <mesh
            geometry={nodes.mesh_22.geometry}
            material={nodes.mesh_22.material}
          />
          <mesh
            geometry={nodes.mesh_23.geometry}
            material={nodes.mesh_23.material}
          />
          <mesh geometry={nodes.mesh_24.geometry} material={materials.AppF6} />
          <mesh geometry={nodes.mesh_25.geometry} material={materials.App957} />
          <mesh geometry={nodes.mesh_26.geometry} material={materials.App286} />
          <mesh
            geometry={nodes.mesh_27.geometry}
            material={nodes.mesh_27.material}
          />
          <mesh
            geometry={nodes.mesh_28.geometry}
            material={nodes.mesh_28.material}
          />
          <mesh
            geometry={nodes.mesh_29.geometry}
            material={nodes.mesh_29.material}
          />
          <mesh
            geometry={nodes.mesh_30.geometry}
            material={materials.App957_0}
          />
          <mesh geometry={nodes.mesh_31.geometry} material={materials.App465} />
          <mesh
            geometry={nodes.mesh_32.geometry}
            material={nodes.mesh_32.material}
          />
          <mesh
            geometry={nodes.mesh_33.geometry}
            material={nodes.mesh_33.material}
          />
          <mesh
            geometry={nodes.mesh_34.geometry}
            material={nodes.mesh_34.material}
          />
          <mesh geometry={nodes.mesh_35.geometry} material={materials.App4F5} />
          <mesh geometry={nodes.mesh_36.geometry} material={materials.AppE57} />
          <mesh geometry={nodes.mesh_37.geometry} material={materials.App424} />
          <mesh
            geometry={nodes.mesh_38.geometry}
            material={nodes.mesh_38.material}
          />
          <mesh
            geometry={nodes.mesh_39.geometry}
            material={nodes.mesh_39.material}
          />
          <mesh geometry={nodes.mesh_40.geometry} material={materials.App477} />
          <mesh geometry={nodes.mesh_41.geometry} material={materials.App037} />
          <mesh
            geometry={nodes.mesh_42.geometry}
            material={nodes.mesh_42.material}
          />
          <mesh
            geometry={nodes.mesh_43.geometry}
            material={nodes.mesh_43.material}
          />
          <mesh geometry={nodes.mesh_44.geometry} material={materials.App0F5} />
          <mesh geometry={nodes.mesh_45.geometry} material={materials.App765} />
          <mesh geometry={nodes.mesh_46.geometry} material={materials.App567} />
          <mesh
            geometry={nodes.mesh_47.geometry}
            material={nodes.mesh_47.material}
          />
          <mesh
            geometry={nodes.mesh_48.geometry}
            material={nodes.mesh_48.material}
          />
          <mesh
            geometry={nodes.mesh_49.geometry}
            material={nodes.mesh_49.material}
          />
          <mesh
            geometry={nodes.mesh_50.geometry}
            material={nodes.mesh_50.material}
          />
          <mesh
            geometry={nodes.mesh_51.geometry}
            material={nodes.mesh_51.material}
          />
          <mesh
            geometry={nodes.mesh_52.geometry}
            material={nodes.mesh_52.material}
          />
          <mesh
            geometry={nodes.mesh_53.geometry}
            material={nodes.mesh_53.material}
          />
          <mesh
            geometry={nodes.mesh_54.geometry}
            material={nodes.mesh_54.material}
          />
          <mesh
            geometry={nodes.mesh_55.geometry}
            material={nodes.mesh_55.material}
          />
          <mesh
            geometry={nodes.mesh_56.geometry}
            material={nodes.mesh_56.material}
          />
          <mesh
            geometry={nodes.mesh_57.geometry}
            material={nodes.mesh_57.material}
          />
          <mesh
            geometry={nodes.mesh_58.geometry}
            material={nodes.mesh_58.material}
          />
          <mesh
            geometry={nodes.mesh_59.geometry}
            material={nodes.mesh_59.material}
          />
          <mesh
            geometry={nodes.mesh_60.geometry}
            material={nodes.mesh_60.material}
          />
          <mesh
            geometry={nodes.mesh_61.geometry}
            material={nodes.mesh_61.material}
          />
          <mesh
            geometry={nodes.mesh_62.geometry}
            material={nodes.mesh_62.material}
          />
          <mesh
            geometry={nodes.mesh_63.geometry}
            material={nodes.mesh_63.material}
          />
          <mesh
            geometry={nodes.mesh_64.geometry}
            material={nodes.mesh_64.material}
          />
          <mesh
            geometry={nodes.mesh_65.geometry}
            material={nodes.mesh_65.material}
          />
          <mesh
            geometry={nodes.mesh_66.geometry}
            material={nodes.mesh_66.material}
          />
          <mesh
            geometry={nodes.mesh_67.geometry}
            material={nodes.mesh_67.material}
          />
          <mesh geometry={nodes.mesh_68.geometry} material={materials.App187} />
          <mesh
            geometry={nodes.mesh_69.geometry}
            material={materials.AppE57_0}
          />
          <mesh geometry={nodes.mesh_70.geometry} material={materials.App456} />
          <mesh
            geometry={nodes.mesh_71.geometry}
            material={nodes.mesh_71.material}
          />
          <mesh
            geometry={nodes.mesh_72.geometry}
            material={nodes.mesh_72.material}
          />
          <mesh
            geometry={nodes.mesh_73.geometry}
            material={nodes.mesh_73.material}
          />
          <mesh
            geometry={nodes.mesh_74.geometry}
            material={nodes.mesh_74.material}
          />
          <mesh
            geometry={nodes.mesh_75.geometry}
            material={nodes.mesh_75.material}
          />
          <mesh
            geometry={nodes.mesh_76.geometry}
            material={nodes.mesh_76.material}
          />
          <mesh
            geometry={nodes.mesh_77.geometry}
            material={nodes.mesh_77.material}
          />
          <mesh
            geometry={nodes.mesh_78.geometry}
            material={nodes.mesh_78.material}
          />
          <mesh geometry={nodes.mesh_79.geometry} material={materials.App825} />
          <mesh geometry={nodes.mesh_80.geometry} material={materials.App256} />
          <mesh
            geometry={nodes.mesh_81.geometry}
            material={nodes.mesh_81.material}
          />
          <mesh
            geometry={nodes.mesh_82.geometry}
            material={nodes.mesh_82.material}
          />
          <mesh
            geometry={nodes.mesh_83.geometry}
            material={nodes.mesh_83.material}
          />
          <mesh
            geometry={nodes.mesh_84.geometry}
            material={nodes.mesh_84.material}
          />
          <mesh
            geometry={nodes.mesh_85.geometry}
            material={nodes.mesh_85.material}
          />
          <mesh
            geometry={nodes.mesh_86.geometry}
            material={nodes.mesh_86.material}
          />
          <mesh geometry={nodes.mesh_87.geometry} material={materials.App8F5} />
          <mesh geometry={nodes.mesh_88.geometry} material={materials.App926} />
          <mesh geometry={nodes.mesh_89.geometry} material={materials.AppA1} />
          <mesh
            geometry={nodes.mesh_90.geometry}
            material={nodes.mesh_90.material}
          />
          <mesh
            geometry={nodes.mesh_91.geometry}
            material={nodes.mesh_91.material}
          />
          <mesh
            geometry={nodes.mesh_92.geometry}
            material={nodes.mesh_92.material}
          />
          <mesh
            geometry={nodes.mesh_93.geometry}
            material={nodes.mesh_93.material}
          />
          <mesh
            geometry={nodes.mesh_94.geometry}
            material={nodes.mesh_94.material}
          />
          <mesh
            geometry={nodes.mesh_95.geometry}
            material={nodes.mesh_95.material}
          />
          <mesh
            geometry={nodes.mesh_96.geometry}
            material={nodes.mesh_96.material}
          />
          <mesh
            geometry={nodes.mesh_97.geometry}
            material={nodes.mesh_97.material}
          />
          <mesh geometry={nodes.mesh_98.geometry} material={materials.App6D5} />
          <mesh geometry={nodes.mesh_99.geometry} material={materials.AppB67} />
          <mesh
            geometry={nodes.mesh_100.geometry}
            material={materials.App925}
          />
          <mesh
            geometry={nodes.mesh_101.geometry}
            material={materials.AppD96}
          />
          <mesh
            geometry={nodes.mesh_102.geometry}
            material={materials.AppC47_0}
          />
          <mesh
            geometry={nodes.mesh_103.geometry}
            material={materials.App2F6}
          />
          <mesh geometry={nodes.mesh_104.geometry} material={materials.AppEB} />
          <mesh
            geometry={nodes.mesh_105.geometry}
            material={nodes.mesh_105.material}
          />
          <mesh
            geometry={nodes.mesh_106.geometry}
            material={nodes.mesh_106.material}
          />
          <mesh
            geometry={nodes.mesh_107.geometry}
            material={nodes.mesh_107.material}
          />
          <mesh
            geometry={nodes.mesh_108.geometry}
            material={nodes.mesh_108.material}
          />
          <mesh
            geometry={nodes.mesh_109.geometry}
            material={nodes.mesh_109.material}
          />
          <mesh
            geometry={nodes.mesh_110.geometry}
            material={nodes.mesh_110.material}
          />
          <mesh
            geometry={nodes.mesh_111.geometry}
            material={nodes.mesh_111.material}
          />
          <mesh
            geometry={nodes.mesh_112.geometry}
            material={nodes.mesh_112.material}
          />
          <mesh
            geometry={nodes.mesh_113.geometry}
            material={nodes.mesh_113.material}
          />
          <mesh
            geometry={nodes.mesh_114.geometry}
            material={nodes.mesh_114.material}
          />
          <mesh
            geometry={nodes.mesh_115.geometry}
            material={materials.App496}
          />
          <mesh
            geometry={nodes.mesh_116.geometry}
            material={materials.App286_0}
          />
          <mesh
            geometry={nodes.mesh_117.geometry}
            material={nodes.mesh_117.material}
          />
          <mesh
            geometry={nodes.mesh_118.geometry}
            material={nodes.mesh_118.material}
          />
          <mesh
            geometry={nodes.mesh_119.geometry}
            material={materials.App424_0}
          />
          <mesh
            geometry={nodes.mesh_120.geometry}
            material={nodes.mesh_120.material}
          />
          <mesh
            geometry={nodes.mesh_121.geometry}
            material={nodes.mesh_121.material}
          />
          <mesh
            geometry={nodes.mesh_122.geometry}
            material={nodes.mesh_122.material}
          />
          <mesh
            geometry={nodes.mesh_123.geometry}
            material={nodes.mesh_123.material}
          />
          <mesh
            geometry={nodes.mesh_124.geometry}
            material={nodes.mesh_124.material}
          />
          <mesh
            geometry={nodes.mesh_125.geometry}
            material={nodes.mesh_125.material}
          />
          <mesh
            geometry={nodes.mesh_126.geometry}
            material={nodes.mesh_126.material}
          />
          <mesh
            geometry={nodes.mesh_127.geometry}
            material={nodes.mesh_127.material}
          />
          <mesh
            geometry={nodes.mesh_128.geometry}
            material={nodes.mesh_128.material}
          />
          <mesh
            geometry={nodes.mesh_129.geometry}
            material={materials.App146}
          />
          <mesh
            geometry={nodes.mesh_130.geometry}
            material={materials.App246_0}
          />
          <mesh
            geometry={nodes.mesh_131.geometry}
            material={nodes.mesh_131.material}
          />
          <mesh
            geometry={nodes.mesh_132.geometry}
            material={nodes.mesh_132.material}
          />
          <mesh
            geometry={nodes.mesh_133.geometry}
            material={materials.App827}
          />
          <mesh
            geometry={nodes.mesh_134.geometry}
            material={materials.AppBB7}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
