/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: lunea (https://sketchfab.com/lunea)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/motorbike-engine-33db399c34ef4d61bd93d422b1c0c92e
title: Motorbike Engine
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function MotorBikeEngine(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "/models/engines/motorBikeEngine/scene.gltf"
  );
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.polySurface299_tloki1_0.geometry}
            material={materials.tloki1}
          />
          <mesh
            geometry={nodes.polySurface299_turbina_txt_0.geometry}
            material={materials.turbina_txt}
          />
          <mesh
            geometry={nodes.polySurface299_wlew_0.geometry}
            material={materials.wlew}
          />
          <mesh
            geometry={nodes.polySurface299_bok2_0.geometry}
            material={materials.bok2}
          />
          <mesh
            geometry={nodes.polySurface299_dol_wydechy1_0.geometry}
            material={materials.dol_wydechy1}
          />
          <mesh
            geometry={nodes.polySurface299_core_dol_0.geometry}
            material={materials.core_dol}
          />
          <mesh
            geometry={nodes.polySurface299_paski1_0.geometry}
            material={materials.paski1}
          />
          <mesh
            geometry={nodes.polySurface299_wydechy1_0.geometry}
            material={materials.wydechy1}
          />
          <mesh
            geometry={nodes.polySurface299_kabelki1_0.geometry}
            material={materials.kabelki1}
          />
          <mesh
            geometry={nodes.polySurface299_pierdoly1_0.geometry}
            material={materials.pierdoly1}
          />
          <mesh
            geometry={nodes.polySurface299_dol_dol1_0.geometry}
            material={materials.dol_dol1}
          />
          <mesh
            geometry={nodes.polySurface299_core_gora_0.geometry}
            material={materials.core_gora}
          />
          <mesh
            geometry={nodes.polySurface299_bok1_0.geometry}
            material={materials.bok1}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
