/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Daniel Zhabotinsky (https://sketchfab.com/DanielZhabotinsky)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/70s-italian-concept-car-669ba2899b9c4c09a495620a78ef852c
title: 70s italian concept car
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function ConceptCar(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/conceptCar/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[42.93, 17.11, 0.97]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <mesh
              geometry={nodes.engine_ZEROPR_ucb_bottom_0.geometry}
              material={nodes.engine_ZEROPR_ucb_bottom_0.material}
            />
          </group>
          <group
            position={[68.57, 21.71, -0.26]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <group position={[-1.97, -0.29, 0.28]}>
              <mesh
                geometry={nodes.brakelights_ZEROPR_brake_lights_0.geometry}
                material={materials.ZEROPR_brake_lights}
              />
            </group>
          </group>
          <group
            position={[-69.72, 10.86, -0.26]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <mesh
              geometry={nodes.headlight_ZEROPR_headlights_ucb_0.geometry}
              material={materials.ZEROPR_headlights_ucb}
            />
          </group>
          <group
            position={[60.27, 13.21, 6.26]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <mesh
              geometry={nodes.exhaust_ZEROPR_ucb_bottom_0.geometry}
              material={nodes.exhaust_ZEROPR_ucb_bottom_0.material}
            />
          </group>
          <group
            position={[49.56, 15.77, -0.36]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <mesh
              geometry={nodes.suspenson_rear_ZEROPR_ucb_bottom_0.geometry}
              material={nodes.suspenson_rear_ZEROPR_ucb_bottom_0.material}
            />
          </group>
          <group
            position={[-34.62, 13.83, -0.16]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <mesh
              geometry={nodes.suspension_front_ZEROPR_ucb_bottom_0.geometry}
              material={nodes.suspension_front_ZEROPR_ucb_bottom_0.material}
            />
          </group>
          <group
            position={[39.93, 29.28, -0.23]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <group position={[-1.02, 0, -0.26]}>
              <mesh
                geometry={nodes.hood_ZEROPR_ucb_bottom_0.geometry}
                material={nodes.hood_ZEROPR_ucb_bottom_0.material}
              />
            </group>
          </group>
          <group
            position={[-0.52, 18.88, -0.26]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <mesh
              geometry={nodes.body__0.geometry}
              material={materials.body__0}
            />
            <mesh
              geometry={nodes.bodypanel_ZEROPR_panel_0.geometry}
              material={materials.ZEROPR_panel}
            />
            <mesh
              geometry={nodes.bodyshel_ZEROPR_body_0.geometry}
              material={nodes.bodyshel_ZEROPR_body_0.material}
            />
            <mesh
              geometry={nodes.Object001_ZEROPR_ucb_interior_0.geometry}
              material={materials.ZEROPR_ucb_interior}
            />
            <mesh
              geometry={nodes.bodyshell_bottom_ZEROPR_ucb_bottom_0.geometry}
              material={nodes.bodyshell_bottom_ZEROPR_ucb_bottom_0.material}
            />
            <mesh
              geometry={nodes.bodyshell_glass_ZEROPR_glass_0.geometry}
              material={nodes.bodyshell_glass_ZEROPR_glass_0.material}
            />
            <mesh
              geometry={nodes.bodyshell_grill_ZEROPR_ucb_grill_0.geometry}
              material={materials.ZEROPR_ucb_grill}
            />
          </group>
          <group
            position={[-22.66, 26.08, -0.26]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <group position={[0.56, 0, -0.18]}>
              <mesh
                geometry={nodes.door_ZEROPR_body_0.geometry}
                material={nodes.door_ZEROPR_body_0.material}
              />
            </group>
            <group position={[0.56, 0, -0.18]}>
              <mesh
                geometry={nodes.door_glass_ZEROPR_glass_0.geometry}
                material={nodes.door_glass_ZEROPR_glass_0.material}
              />
            </group>
          </group>
          <group
            position={[-34.2, 9.73, 26.07]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <group scale={0.61}>
              <mesh
                geometry={nodes.wheel_front_left_ZEROPR_rim_0.geometry}
                material={nodes.wheel_front_left_ZEROPR_rim_0.material}
              />
            </group>
            <group scale={0.61}>
              <mesh
                geometry={nodes.tire_ZEROPR_tire_0.geometry}
                material={nodes.tire_ZEROPR_tire_0.material}
              />
            </group>
          </group>
          <group
            position={[49.21, 12.15, 27.41]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <group scale={[0.61, 0.77, 0.61]}>
              <group position={[0, 0.02, 0]}>
                <mesh
                  geometry={nodes.tire_rear_ZEROPR_tire_0.geometry}
                  material={nodes.tire_rear_ZEROPR_tire_0.material}
                />
              </group>
            </group>
            <group scale={[0.61, 0.77, 0.61]}>
              <group position={[0, 0.02, 0]}>
                <mesh
                  geometry={nodes.wheel_rear_left_ZEROPR_rim_0.geometry}
                  material={nodes.wheel_rear_left_ZEROPR_rim_0.material}
                />
              </group>
            </group>
          </group>
          <group
            position={[-34.2, 9.73, -29.28]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <group scale={0.61}>
              <mesh
                geometry={nodes.wheel_front_left001_ZEROPR_rim_0.geometry}
                material={nodes.wheel_front_left001_ZEROPR_rim_0.material}
              />
            </group>
            <group scale={0.61}>
              <mesh
                geometry={nodes.tire001_ZEROPR_tire_0.geometry}
                material={nodes.tire001_ZEROPR_tire_0.material}
              />
            </group>
          </group>
          <group
            position={[49.21, 12.15, -27.94]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={39.49}
          >
            <group scale={[0.61, 0.77, 0.61]}>
              <group position={[0, 0.02, 0]}>
                <mesh
                  geometry={nodes.tire_rear001_ZEROPR_tire_0.geometry}
                  material={nodes.tire_rear001_ZEROPR_tire_0.material}
                />
              </group>
            </group>
            <group scale={[0.61, 0.77, 0.61]}>
              <group position={[0, 0.02, 0]}>
                <mesh
                  geometry={nodes.wheel_rear_left001_ZEROPR_rim_0.geometry}
                  material={nodes.wheel_rear_left001_ZEROPR_rim_0.material}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
