/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Karol Miklas (https://sketchfab.com/karolmiklas)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-gmc-motorhome-reimagined-low-poly-6hiH0iyDqXqtdD9wbqSbyLLhKmz
title: FREE GMC Motorhome reimagined low poly
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Gmc(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/gmc/scene.gltf");
  return (
    <group ref={group} {...props} scale={1.3} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0.76, 0.24, 3.4]}
            rotation={[-0.14, 0, 0.01]}
            scale={[1.06, 1.06, 1.06]}
          >
            <mesh
              geometry={nodes.mesh_0.geometry}
              material={nodes.mesh_0.material}
            />
          </group>
          <group position={[0.84, 0.29, 3.48]}>
            <mesh
              geometry={nodes.mesh_1.geometry}
              material={nodes.mesh_1.material}
            />
          </group>
          <group position={[0.75, 0.13, 2.73]} scale={[0.25, 0.29, 0.25]}>
            <mesh
              geometry={nodes.mesh_2.geometry}
              material={nodes.mesh_2.material}
            />
          </group>
          <group scale={1.17}>
            <mesh
              geometry={nodes.mesh_3.geometry}
              material={nodes.mesh_3.material}
            />
          </group>
          <group position={[-0.66, 0.29, 3.48]}>
            <mesh
              geometry={nodes.mesh_4.geometry}
              material={nodes.mesh_4.material}
            />
          </group>
          <group
            position={[-0.75, 0.1, 2.85]}
            rotation={[-Math.PI, 0.46, -Math.PI]}
            scale={[0.25, 0.29, 0.25]}
          >
            <mesh
              geometry={nodes.mesh_5.geometry}
              material={nodes.mesh_5.material}
            />
          </group>
          <group scale={1.17}>
            <mesh
              geometry={nodes.mesh_6.geometry}
              material-color={props.customColor}
              material={materials.clay}
            />
          </group>
          <group
            position={[0, -0.96, 3.06]}
            rotation={[-0.48, 0, 0]}
            scale={1.17}
          >
            <mesh
              geometry={nodes.mesh_7.geometry}
              material={nodes.mesh_7.material}
            />
          </group>
          <group
            position={[0, -0.96, -1.14]}
            rotation={[0.25, 0, 0]}
            scale={1.17}
          >
            <mesh
              geometry={nodes.mesh_8.geometry}
              material={nodes.mesh_8.material}
            />
          </group>
          <group
            position={[0, -0.96, -2.19]}
            rotation={[-1.2, 0, 0]}
            scale={1.17}
          >
            <mesh
              geometry={nodes.mesh_9.geometry}
              material={nodes.mesh_9.material}
            />
          </group>
          <group scale={1.17}>
            <mesh
              geometry={nodes.mesh_10.geometry}
              material={materials.windows}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
